title: Data Science Project – Time Series Analysis on Cleveland Police Crime Data: March 2022 to February 2025
#logo: /assets/shrink_logo.png
#description: Test Portfolio
show_downloads: true
theme: jekyll-theme-minimal
